/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Cedric DELHOME
 */
public class FlightView extends javax.swing.JPanel {

    /**
     * Creates new form FlightView
     */
    public FlightView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelTable = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanelInfo = new javax.swing.JPanel();
        jPanelInfoLeft = new javax.swing.JPanel();
        jLabelNumFlight = new javax.swing.JLabel();
        jLabelCityStart = new javax.swing.JLabel();
        jLabelCountryStart = new javax.swing.JLabel();
        jLabelIATAStart = new javax.swing.JLabel();
        jLabelCityArrived = new javax.swing.JLabel();
        jLabelCountryArrived = new javax.swing.JLabel();
        jLabelIATAArrived = new javax.swing.JLabel();
        jLabelDateStart = new javax.swing.JLabel();
        jLabelHoursStart = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanelInfoRight = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(2, 0));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jPanelTable.setViewportView(jTable);

        add(jPanelTable);

        jPanelInfo.setLayout(new java.awt.GridLayout(1, 2));

        jPanelInfoLeft.setLayout(new java.awt.GridBagLayout());

        jLabelNumFlight.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNumFlight.setText("N° de vol");
        jLabelNumFlight.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jLabelNumFlight, gridBagConstraints);

        jLabelCityStart.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCityStart.setText("Ville de départ");
        jLabelCityStart.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jLabelCityStart, gridBagConstraints);

        jLabelCountryStart.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCountryStart.setText("Pays de départ");
        jLabelCountryStart.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jLabelCountryStart, gridBagConstraints);

        jLabelIATAStart.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIATAStart.setText("Code aéroport de départ");
        jLabelIATAStart.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jLabelIATAStart, gridBagConstraints);

        jLabelCityArrived.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCityArrived.setText("Ville d'arrivée");
        jLabelCityArrived.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jLabelCityArrived, gridBagConstraints);

        jLabelCountryArrived.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCountryArrived.setText("Pays d'arrivée");
        jLabelCountryArrived.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jLabelCountryArrived, gridBagConstraints);

        jLabelIATAArrived.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIATAArrived.setText("Code aéroport d'arrivée");
        jLabelIATAArrived.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jLabelIATAArrived, gridBagConstraints);

        jLabelDateStart.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDateStart.setText("Date de départ");
        jLabelDateStart.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jLabelDateStart, gridBagConstraints);

        jLabelHoursStart.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHoursStart.setText("Heure de départ");
        jLabelHoursStart.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jLabelHoursStart, gridBagConstraints);

        jTextField1.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jTextField1, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jComboBox1, gridBagConstraints);

        jTextField2.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jTextField2, gridBagConstraints);

        jTextField3.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jTextField3, gridBagConstraints);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jComboBox2, gridBagConstraints);

        jTextField4.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jTextField4, gridBagConstraints);

        jTextField5.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jTextField5, gridBagConstraints);

        jTextField6.setPreferredSize(new java.awt.Dimension(150, 25));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jTextField6, gridBagConstraints);

        jTextField7.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanelInfoLeft.add(jTextField7, gridBagConstraints);

        jPanelInfo.add(jPanelInfoLeft);

        javax.swing.GroupLayout jPanelInfoRightLayout = new javax.swing.GroupLayout(jPanelInfoRight);
        jPanelInfoRight.setLayout(jPanelInfoRightLayout);
        jPanelInfoRightLayout.setHorizontalGroup(
            jPanelInfoRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        jPanelInfoRightLayout.setVerticalGroup(
            jPanelInfoRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        jPanelInfo.add(jPanelInfoRight);

        add(jPanelInfo);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabelCityArrived;
    private javax.swing.JLabel jLabelCityStart;
    private javax.swing.JLabel jLabelCountryArrived;
    private javax.swing.JLabel jLabelCountryStart;
    private javax.swing.JLabel jLabelDateStart;
    private javax.swing.JLabel jLabelHoursStart;
    private javax.swing.JLabel jLabelIATAArrived;
    private javax.swing.JLabel jLabelIATAStart;
    private javax.swing.JLabel jLabelNumFlight;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelInfoLeft;
    private javax.swing.JPanel jPanelInfoRight;
    private javax.swing.JScrollPane jPanelTable;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
